# Generated by Django 3.2.9 on 2022-02-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_tag_editable'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(unique=True)),
                ('value', models.TextField(default=None, null=True)),
            ],
        ),
    ]
