# Generated by Django 3.2.9 on 2022-02-12 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_settingsentry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SettingsEntry',
            new_name='ConfigEntry',
        ),
    ]
