# Generated by Django 3.2.9 on 2022-02-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_settingsentry_configentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=None)),
                ('ip', models.TextField()),
                ('session', models.TextField()),
            ],
        ),
    ]
