# Generated by Django 4.0.3 on 2022-03-07 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_stat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256, unique=True)),
                ('path', models.TextField()),
                ('dl_count', models.IntegerField(default=0)),
                ('comment', models.TextField()),
            ],
        ),
    ]
